#spring.application.name=strava-club-collector

############################################
# Spring Application
############################################
spring.application.name=StravaCC
server.port=8080


############################################
# Datasource Configuration (PostgreSQL)
############################################
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver


############################################
# JPA / Hibernate
############################################
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true


############################################
# Connection Pool (HikariCP)
############################################
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.max-lifetime=600000


############################################
# Strava Base Configuration
############################################
strava.base-url=https://www.strava.com/api/v3
strava.club-id=1821074


############################################
# Strava OAuth Configuration
############################################
strava.oauth.client-id=185713
strava.oauth.client-secret=0f51b42ee490293a12e1cb1e58cb46466ea87d49
strava.oauth.redirect-uri=http://localhost:8080/oauth/callback


############################################
# Strava OAuth Token State (auto-managed)
############################################
strava.auth.access-token=1c59e0f3580b572201170dd3698f0b50a6094a4b
strava.auth.refresh-token=45405914a8cb5ad13195a8e37ab6d3f356b56053
strava.auth.expires-at=0


############################################
# Strava Fetch Behaviour
############################################
strava.fetch.per-page=200
strava.fetch.max-pages=1
strava.fetch.max-records=5000
strava.fetch.poll-interval-ms=600000


############################################
# Logging
############################################
logging.level.root=INFO
logging.level.com.closecircuit.strava=DEBUG
logging.level.org.springframework.web.reactive.function.client.ExchangeFunctions=INFO


############################################
# Actuator
############################################
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
